# This file was *autogenerated* from the file mAp6.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)


def mAp6(Cs, LS):

	polygon([(_sage_const_0 ,_sage_const_0 ) , (_sage_const_1 , _sage_const_1 ), (_sage_const_0 , _sage_const_1 )]).show()

mAp6(_sage_const_1 , _sage_const_1 )
