# This file was *autogenerated* from the file mod6.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from math import pi, cos 
from random import random 

def m6p1(n):
    skipti=_sage_const_0 
    count=_sage_const_0 
    while count<n: 
       d=random()
       horn=random()*pi/_sage_const_2 
       if d<=cos(horn):
          skipti+=_sage_const_1 
       count+=_sage_const_1 
    return skipti/n 


def m6p3(x,y, rad=_sage_const_2 ):
       
    if(x**_sage_const_2  + y**_sage_const_2  < rad**_sage_const_2 ) and x is not _sage_const_0  and y is not _sage_const_0 :                                                                                                                
        return True
    else:    
        return False
